name: truck_trip_app
description: Truck Trip Management mobile app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
flutter:
  uses-material-design: true
