import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import auth from './routes/auth.js';
import trucks from './routes/trucks.js';
import drivers from './routes/drivers.js';
import trips from './routes/trips.js';
import expenses from './routes/expenses.js';
import reports from './routes/reports.js';
dotenv.config();
const app=express();
app.use(cors());
app.use(express.json());
app.use('/uploads',express.static('uploads'));
app.get('/api/health',(req,res)=>res.json({success:true}));
app.use('/api/auth',auth);
app.use('/api/trucks',trucks);
app.use('/api/drivers',drivers);
app.use('/api/trips',trips);
app.use('/api/expenses',expenses);
app.use('/api/reports',reports);
app.listen(process.env.PORT||4000,()=>console.log('API running on port '+(process.env.PORT||4000)));
